name: da_spice
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ">=2.19.0-444.2.beta <3.0.0"

dependencies:
  args: ^2.3.0
  ffi: ^2.0.1
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  ffigen: ^7.2.4
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0

ffigen:
  output: "lib/ng_spice/generated_bindings.dart"
  headers:
    entry-points:
      - "3rd_pkg/ngspice/src/include/ngspice/sharedspice.h"
